### ISSUE TITLE
Throttling scroll or resize event by `requestAnimationFrame` may be unnecessary

### ISSUE THREAD

**Issue by cnlon** [pelotoncycle/frame-throttle#7]
The `scroll` or `resize` event and animation frames are fired at about the same rate and therefore the throttle by `requestAnimationFrame` may be unnecessary.
See: <https://developer.mozilla.org/en-US/docs/Web/Events/scroll>

**Comment by devrelm** [comment]
I read that section differently. The first two sentences go together:

> Since `scroll` events can fire at a high rate, the event handler shouldn't execute computationally expensive operations such as DOM modifications. Instead, it is recommended to throttle the event using `requestAnimationFrame`, `setTimeout` or `customEvent`, as follows.

The last sentence is worded a little ambiguously, especially being part of the same paragraph and immediately following the two sentences above:

> Note however that input events and animation frames are fired at about the same rate and therefore the optimization below is often unnecessary.

I read that as: "Note however that input events are fired at about the same rate as animation frames and therefore the optimization below is often unnecessary."

So in essence: input events (for instance, repeated text-input `change` events due to holding down the spacebar) happen at or below the framerate, but `scroll` events still happen faster than the framerate.
